import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div>
          <form>
            <input type="text" />
          </form>
        </div>
        <h1>example</h1>
      </div>
    </>
  );
}
